- src/components/vanilla/controls/DateRangePicker/index.tsx
- src/components/vanilla/controls/Dropdown/index.tsx
When the user selects NoFilter, the component doesn't update to show that selection.
There is no update of the relative date picker.
Fix both.
https://github.com/embeddable-hq/vanilla-components/assets/57071299/22762f79-434b-42e3-ac33-05cffc7885de
> EM-542: date range picker no filter

- .github/workflows/npm-audit.yml
Configures Github Action to run `npm:audit` daily at 10AM and report failures to Slack
> Run npm:audit in CI workflow

- README.md
Updates Node version mentioned in documentation to 20.
The code change was done in scope of https://github.com/embeddable-hq/vanilla-components/commit/a05084b484f8f1664bcb0bb291a0e39eb6dba024
> Update minimal node version to 20

- src/components/vanilla/controls/DatePicker/components/DateRangePicker.tsx
- src/components/vanilla/controls/DatePicker/components/DateRangeWithGranularity.tsx
- src/components/vanilla/controls/DatePicker/utils/dateUtils.ts
Fix bug whereby the period in the date range picker was diverging from Embeddable state (causing the date dropdown to have to be clicked twice)
- Minor styling changes, including only showing a single date in the comparison picker for single days
- Additional period added to relative time string options in dropdown ('6 months')
> Bug fix in datepicker

- src/components/util/format.ts
Resolves an issue where PivotTable dates were displaying differently depending on the user's timezone (eg: not showing 10/29 for users in Pacific Time despite data coming in from 10/29 UTC).
Fixes TPS-358
It's a little complicated to replicate this - you need to create a pivot table that contains dates, set your granularity to day, then manually change your computer over to a different timezone that's behind UTC, and then test against data that exists for the current UTC date. I've done this and can confirm that the code change works. I correctly see data for 10/29 (the date of this PR) even when set to San Francisco time.
Here's a screenshot of it working - before the fix the last date in the table was 10/28. With the fix, even in Pacific time, the last date in …
> TPS-358 - Pivot Table Time Zone

- embeddable.config.js
- src/scripts/connection-create.cjs
- src/scripts/connection-list.cjs
- src/scripts/connection-read.cjs
- src/scripts/connection-test.cjs
- src/scripts/connection-update.cjs
- src/scripts/embedding-preview.cjs
Adjusts the API URIs in a handful of connection files to reflect the current availability of https://api.us.embeddable.com and https://api.eu.embeddable.com
If the US and EU URIs look correct in the code, we should be good to go.
> Update API URIs to correct current values

- package-lock.json
- package.json
- src/components/util/downloadAsPNG.ts
- yarn.lock
We caught an issue where charts that use canvas were rendering as blank in Safari. This is a known issue with the rendering library we were using, so I fixed it by falling back to a previous library (which doesn't work well in chromium browsers) only if the user is on Safari.
Acceptance Criteria:
- Charts should render as PNGs in Chrome, Edge, Firefox, and Safari (they do)
- Code should only use html2canvas in cases where the browser is identified as Safari (it does)
> Fix PNG rendering too quickly for canvas in Safari

- src/components/util/getBarChartOptions.ts
- src/components/vanilla/charts/BarChart/BarChart.emb.ts
- src/components/vanilla/charts/BarChart/TimeSeriesBarChart.emb.ts
- src/components/vanilla/charts/BarChart/components/BarChart.tsx
- src/components/vanilla/charts/BarChart/index.tsx
Line metric option added to bar chart and time-series bar chart. 
The user can select multiple metrics, and also choose whether to show these on a separate right-side axis. The user can optionally also add a title to this right-axis.
> Line display option added to bar charts

- src/components/util/format.ts
- src/components/util/getBarChartOptions.ts
- src/components/vanilla/charts/BarChart/components/BarChart.tsx
- src/components/vanilla/charts/BubbleChart/index.tsx
- src/components/vanilla/charts/KPIChart/index.tsx
- src/components/vanilla/charts/LineChart/LineChart.emb.ts
- src/components/vanilla/charts/LineChart/index.tsx
- src/components/vanilla/charts/PieChart/index.tsx
- src/components/vanilla/charts/PivotTable/PivotTable.tsx
- src/components/vanilla/charts/ScatterChart/index.tsx
- src/components/vanilla/charts/StackedAreaChart/index.tsx
- src/models/cubes/products.cube.yml
You can now add pre and post-text meta to your models, like so:
```
- name: price
type: sum
title: Total USD
sql: price_usd
meta: 
pretext: '$'
posttext: ''
```
and it will automatically add these within the vanilla repo code via the format function, where those measures are displayed.
I've updated quite a few files. I've played with this and it works, but please test this.
> Format function for measures now receives pretext and posttext meta

- src/components/vanilla/charts/StackedBarChart/StackedBarChart.emb.ts
Fulfills the request mentioned here: https://charts-roadmap.embeddable.com/roadmap/add-sorting-on-the-x-axis-to-the-stacked-bar-chart
"In the bar chart component you can specify how to sort the position of the bars in the X axis, it would be great to have this ability in the stacked bar chart as well."
- Code should look good
- Stacked Bar Chart should order by the user's choice (see screenshot)
- Stacked Bar Chart should be able to be reversed (see second screenshot)
Sorted by Product Name:
Reversed:
> add sorting and reverse x axis to stacked bar chart

- src/components/vanilla/controls/DatePicker/components/DateRangePicker.tsx
- src/components/vanilla/controls/GranularityPicker/GranularityPicker.emb.ts
- src/components/vanilla/controls/GranularityPicker/index.tsx
An end-user can update the granularity. 
It will update the date range based on the granularity (e.g. if the user selects day, it will show the last 30 days. If they select year, it will show all time)
> Granularity picker

- src/components/vanilla/charts/DownloadButton/DownloadButton.emb.ts
- src/components/vanilla/charts/DownloadButton/index.tsx
Previously, the download button snagged data when the Embeddable loaded. This meant with large datasets it would spin and spin, whether or not the user ever intended on downloading the data. We've changed the behavior using embeddable state so that the results are only loaded on click
Note: we're continuing to also use a local state variable for the spinner because I didn't want to rewrite the download CSV function to handle the nested state from `useEmbeddableState` and overcomplicate this PR, but I'm open to pushback on that.
> Download Button - Wait for Click to Load Data

- src/components/util/chartjs/common.ts
- src/components/util/dataUtils.ts
- src/components/util/getBarChartOptions.ts
- src/components/util/getStackedChartData.ts
- src/components/vanilla/charts/BubbleChart/index.tsx
- src/components/vanilla/charts/CompareLineChart/index.tsx
- src/components/vanilla/charts/LineChart/index.tsx
- src/components/vanilla/charts/ScatterChart/index.tsx
- src/components/vanilla/charts/StackedAreaChart/index.tsx
- src/models/cubes/customers.cube.yml
- Chart axes are now formatted (e.g. will appear as 2,000 rather than 2000)
- Logic added to deal with small number fractions: chartJS would previously add a fractional stepsize even if the data only contained whole numbers.  Now it shows fractions only if the data contains fractions, unless the user specifies a specific dp. 
- Bug fixed whereby stacked charts would always show whole numbers even if the data contained fractions
https://github.com/user-attachments/assets/9835aeb0-f389-4a43-bff0-fb726daeeda9
> Format axes

- src/components/util/getBarChartOptions.ts
- src/components/util/getStackedChartData.ts
- src/components/vanilla/charts/BubbleMapChart/BubbleMapChart.emb.ts
- src/components/vanilla/charts/KPIChart/KPIChartText.emb.ts
- src/components/vanilla/charts/LineChart/LineChart.emb.ts
- src/components/vanilla/charts/StackedAreaChart/MultiDimensionLineChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/StackedBarChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/TimeSeriesStackedBarChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/index.tsx
- A 'stacked' boolean input has been added to the stacked bar chart. When set to true, the bars are stacked. When set to false, the bars are grouped together (based on the x-axis value), but not-stacked. 
- % option modified so, when grouped, it doesn't set a max-y-value of 100.  
Additionally, stacked charts name updated to "grouped charts". 
- I've done this to create a consistent naming convention for the scenario where we have different chart options for multi-metric and multi-dimension data inputs. Multi-metric is now the standard (e.g. bar chart, line chart). Multi-dimension (e.g. stacked bar chart, multi-dimension line chart) is now 'grouped'.
- I've discovered an issue for the 'show totals above stacked bars' option. When "display as %" is selected, the total should show 100 but …
> Non-stacked option added to stacked bar charts.

- src/components/util/chartjs/common.ts
- src/components/vanilla/charts/BarChart/components/BarChart.tsx
- src/components/vanilla/charts/BarChart/index.tsx
- src/components/vanilla/charts/PieChart/index.tsx
- src/defaulttheme.ts
**Note: this is being merged to develop, not main**
This PR moves the pie chart away from using `constants.ts` and instead uses the theme values being passed in via the client repo (not currently visible, will fix that shortly so people can see what I'm doing over there 😁 )
I had to tweak a few things in the bar chart to go along with the changes I realized I needed to make to get the pie chart working. This will happen a bit here and there as we get more charts up and running and realize we need to tweak the theme structure. You can see the tweaks to the theme structure in the default file (the celtics file is in my client repo, see above)
- Code looks good
- Pie chart changes color with theme change (see screenshots)
- Pie chart changes font with theme change …
> Move Pie Charts to Themes

- src/components/vanilla/charts/BarChart/index.tsx
- src/components/vanilla/charts/TableChart/index.tsx
This moves the table charts away from constants and instead uses the new theming system.
> Move Table to Using Themes

- src/components/vanilla/charts/BubbleChart/index.tsx
- src/components/vanilla/charts/CompareLineChart/index.tsx
- src/components/vanilla/charts/PieChart/index.tsx
- src/defaulttheme.ts
This moves the table charts away from constants and instead uses the new theming system.
> Change Comparison Line Chart to Use Themes

- src/components/vanilla/charts/TableChart/TableChart.emb.ts
- src/components/vanilla/charts/TableChart/index.tsx
If you have a table that's linked to a variable, and you're on, say, page 5 of the table, and you change the variable to something that reduces the table length to only one or two pages, then you'll get a table showing nothing because you're on page 5 of a 2 page table.
See this video: https://us06web.zoom.us/clips/share/A2F3MRY2dHk2T3VrTFFsSzdTdmIxaTZ2YjhRAQ
**Desired Behavior**
If the table's dataset changes (other than for paging purposes), reset the page to zero.
- Code should look good
- Table should reset to page 1 if any variable changes happen
**Video Evidence**
https://www.loom.com/share/a61f00baf0c340c1aa7f16316788911a?sid=e33d2dff-7203-4606-8502-212974fdb861
> Update Table to Reset to Page 1 if Variables Change

- src/components/vanilla/charts/PivotTable/PivotTable.tsx
- src/components/vanilla/charts/PivotTable/components/TableHead.tsx
- src/components/vanilla/charts/PivotTable/core/useTableColumns.ts
This moves the pivot table away from constants and instead uses the new theming system.
> Move Pivot Table to Using Themes

- src/components/util/getStackedChartData.ts
- src/components/vanilla/charts/StackedBarChart/index.tsx
This moves the stacked bar charts away from constants and instead uses the new theming system.
> Stacked Bar Chart Now Uses Themes

- src/components/util/getBarChartOptions.ts
Show '100' as the total when displayAsPercentage is true
Don't show the total at all if the bars are not stacked
**Issue**
The 'grouped bar chart' has a show as % option, and also has a 'show totals above bars' option. If both of these are true, the totals above the bars should always be "100", but currently it shows the sum of the original values (not the %s)
> Grouped bar totals - fix for %s

- src/components/util/getBarChartOptions.ts
The stacked bar chart was throwing an error in certain cases where an xAxis was being generated but had no data, and totals were set to display. This was causing issues for a client who had small amounts of data over a large time span, causing a lot of zero-data xAxis items to be generated (a bunch of dates w/ no data).
The fix for this is straightforward. Add an undefined check while putting together the data needed to display the totals.
- Code works (client verified this already, I asked them to make the change manually)
- Code looks good!
> Fix TPS-565 - Stacked Bar Chart Erroring w/ Undefined Data

- src/components/icons/Checkbox.tsx
- src/components/icons/CheckboxEmpty.tsx
- src/components/vanilla/controls/MultiSelectDropdown/index.tsx
In multi-select dropdowns where the text is very long (or the dropdown size very small), the dropdown resizes the checkboxes making them either tiny (and hard to click) or nonexistent (and impossible to click). Ensure that it gives preference to the checkbox and always keeps it the same size, and overflows the text instead.
- All checkboxes are always the same size and always visible.
**Before**
**After**
> Fix checkbox sizing issue

- src/components/vanilla/charts/DynamicAxisBar/index.tsx
In dynamic axis chart, check that any of the first 10 results contain the updated xAxis value, not just the first row (which might be null)
> Dynamic Axis Barchart fix

- src/components/vanilla/controls/GranularityPicker/GranularityPicker.emb.ts
- src/components/vanilla/controls/GranularityPicker/index.tsx
Currently you can't set a title on the granularity picker. One of our clients would like to do so. This makes it possible.
This change looks bigger than it is because prettier reformatted a bunch of stuff. things that actually changed:
`GranularityPicker.emb.ts`:
```
{
name: 'title',
type: 'string',
label: 'Title',
defaultValue: '',
category: 'Chart settings',
},
```
`index.tsx`
- Added `title` to props
- Grab `title` from props
- Pass `title` to `Container`
> Add ability to include title in granularity picker

- src/components/vanilla/charts/DownloadButton/DownloadButton.emb.ts
- src/components/vanilla/charts/DownloadButton/index.tsx
We've had numerous reports from clients that the download button doesn't always behave as expected, giving truncated or otherwise incorrect data. After investigation, I found that only the first click of the download button was correctly giving data - after that it was fighting race conditions and often initiating a download on the previous data before the new data had finished loading.
**Solution**
I introduced a new state value that contains the last-downloaded data. We then compare the data that the button is attempting to download with the last-downloaded data and, if they're the same, we wait until the new `loadData` has finished before firing the download (and replacing the last-downloaded data state). This works consistently and should solve the issues with the …
> TPS-618 - Download Button Doesn't Always Respond to Filters

- src/components/vanilla/charts/DynamicAxisBar/index.tsx
Updating the dynamic axis bar chart then changing the data caused it to revert to the original x-axis value even though the dropdown still showed the new one (this also prevented the bar chart from display). See here for more: https://trevorio.atlassian.net/issues/TPS-682
**Fix**
There was a `useEffect` running every time the x-axis changed resetting it to the `props` value ... but that was running whenever the data changed because by default it sends a new set of props when new data is pulled in. It's not needed since we run the same `setValue` command when the dropdown changes anyway. This way we retain the selected item between data changes, which is the experience a user would expect.
> TPS-682 - Ensure Dynamic X-Axis Value Remains When Data Updates

- src/components/vanilla/Container.tsx
- src/components/vanilla/DownloadMenu.tsx
- src/components/vanilla/charts/TableChart/TableChart.emb.ts
- src/components/vanilla/charts/TableChart/index.tsx
We have a lot of clients who don't love that the "download as CSV" option on the table only downloads one page of data. Rather than grabbing the entire dataset every single time and doing paging specifically on the front-end, I added a solution that does a second `loadData` but with a zero limit, unless a certain state value is `true`. This allows us to only load the full dataset when it's actually being requested, and in addition prevents issues with props "caching" (to be investigated by engineering at a later date).
> CS-16 - Add Download All as CSV button to Table component

- src/components/vanilla/controls/Dropdown/index.tsx
** Description **
Due to the fix for the scrollbar issue on dropdowns (where dragging the scrollbar would cause a `blur` and the window would shut while you were dragging), once you selected an option, you could not open the dropdown again unless you clicked somewhere else on the page. This was annoying and confusing. It's now fixed.
** Acceptance Criteria **
> CS-66 - Dropdowns Not Recognizing Second Click

- src/components/vanilla/DownloadMenu.tsx
The download all selection in the download menu, being a link, needs to be default prevented in order to avoid strange behavior when embedded in the client repo.
> TPS-709 - Download All Button Is an Un-default-prevented Link

- src/components/vanilla/charts/PieChart/index.tsx
**description**
A customer noticed at when using a pie chart with boolean values, the tooltip label would show "true" for true, but nothing for "false". The reason is this line:
```
let label = context.dataset.label || '';
```
Because if `label` is `false`, it just sets an empty string. So I added an additional few lines to explicitly check for boolean values. I tried a few different ways of structuring the code, but this was the shortest working version.
> TPS-721 - Handle pie chart labels that are booleans

- .gitignore
- src/components/vanilla/DownloadMenu.tsx
- src/components/vanilla/controls/Dropdown/index.tsx
- src/components/vanilla/controls/MultiSelectDropdown/index.tsx
In order to be in compliance for the late-June EU accessibility requirements for public sector websites (which we aren't, but some of our clients our clients' clients are), we need to add keyboard accessibility to a few sections of Vanilla that are currently lacking it. Specifically, the dropdown, multi-select dropdown, and download menu
> Add keyboard accessibility to dropdown, multiselect, and download menu

- src/components/vanilla/charts/CompareLineChart/index.tsx
Fixes bug where comparison line chart crashes if secondary xAxis title isn't given. This fix is already tested and working in VC v1 (and also by one of our clients using VC v0, which is how I confirmed I'd missed it in this repo!).
> Fix - Comparison Line

- src/components/util/format.ts
- src/components/vanilla/charts/TableChart/index.tsx
Checks all table column values to see if any of them are markdown formatted links. If so, it returns an anchor dom element with the appropriate text/href, rather than just plain text.
I went ahead and left the sample link measure in the model file, as it may be useful for us down the line when testing other things
**Screenshot**
Browser showing that the text is an active link (see bottom left corner)
> CS-27 - Support Markdown in Table Links

- package-lock.json
- package.json
- src/components/vanilla/charts/BarChart/components/BarChart.tsx
- Bar chart respects granularity sub input
- Bar chart has a default date format if granularity isn't set, instead of displaying the entire UTC string
Note: this is identical to [the V1 PR](https://github.com/embeddable-hq/vanilla-components-v1/pull/98) it's just that prettier reformatted a bunch of stuff.
> Fix - Bar Chart Granularity

- src/components/vanilla/charts/PivotTable/PivotTable.tsx
- src/components/vanilla/charts/TableChart/index.tsx
- src/models/cubes/orders.cube.yml
This fixes an issue where boolean values coming in from models were being displayed as empty spaces in both the standard and pivot tables. We now return the string value of the boolean in all cases.
Also adds an example boolean to the Orders model in case we need to do future testing
> TPS-848 - Tables don't display boolean values

- .gitignore
- embeddable.config.js
- package-lock.json
- package.json
- src/components/vanilla/charts/BarChart/BarChart.emb.ts
- src/components/vanilla/charts/BarChart/TimeSeriesBarChart.emb.ts
- src/components/vanilla/charts/BubbleChart/BubbleChart.emb.ts
- src/components/vanilla/charts/BubbleMapChart/BubbleMapChart.emb.ts
- src/components/vanilla/charts/CompareLineChart/CompareLineChart.emb.ts
- src/components/vanilla/charts/DownloadButton/DownloadButton.emb.ts
- src/components/vanilla/charts/DynamicAxisBar/DynamicAxisBar.emb.ts
- src/components/vanilla/charts/KPIChart/KPIChart.emb.ts
- src/components/vanilla/charts/KPIChart/KPIChartText.emb.ts
- src/components/vanilla/charts/KPIChart/SimpleKPIChart.emb.ts
- src/components/vanilla/charts/LineChart/LineChart.emb.ts
- src/components/vanilla/charts/MapChart/MapChart.emb.ts
- src/components/vanilla/charts/PieChart/PieChart.emb.ts
- src/components/vanilla/charts/PivotTable/PivotTable.emb.ts
- src/components/vanilla/charts/ScatterChart/ScatterChart.emb.ts
- src/components/vanilla/charts/StackedAreaChart/MultiDimensionLineChart.emb.ts
- src/components/vanilla/charts/StackedAreaChart/StackedAreaChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/StackedBarChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/TimeSeriesStackedBarChart.emb.ts
- src/components/vanilla/charts/TableChart/TableChart.emb.ts
- src/components/vanilla/controls/Dropdown/Dropdown.emb.ts
- src/components/vanilla/controls/MultiSelectDropdown/MultiSelectDropdown.emb.ts
This PR introduces automatic granularity support to all components in the vanilla-components repository, aligning with the recent migration to the unified select array API structure.
- Updated all `loadData` calls across 24 components to use the new `select` array instead of separate `dimensions`, `measures`, and `timeDimensions` parameters
- This change enables components to handle TimeDimension objects with granularity specifications
Added `hideGranularity: true` to components that already have their own granularity controls to prevent duplicate pickers:
- Time series charts (TimeSeriesBarChart, LineChart, CompareLineChart, etc.)
- Components with time-based dimensions (DynamicAxisBar, BubbleChart, ScatterChart)
- Multi-dimensional charts (StackedAreaChart, MultiDimensionLineChart, …
> EM-2144: Enable automatic granularity support in all components

- src/components/vanilla/charts/TableChart/index.tsx
Fixed an issue in the table component where the client's data has null in what is otherwise a string column was throwing an error and breaking the table. Having null in a string return is slightly malformed on their part but we should still check for it. Now null values (and undefined) generate a simple '-' string to get inserted into the table at the appropriate place.
Reason for the error: null is technically an object in JavaScript, so another part of the code was seeing that and trying to look for null.props.children which ... isn't a thing. This is happening because the only time we send an object, it's from custom code that allows users to put markdown links into their data and have them format correctly. We could make that code more robust, but this is a one-line fix we can get in …
> TPS-873 - Table Throwing Error on Sort

- src/components/vanilla/charts/BarChart/components/BarChart.tsx
A small change that allows the v0 version of the time series bar chart to continue using the date/time formats found in the constants file. Basically, we updated the check to look for the native granularity value now that time dimensions automatically get one ... but then we disabled the automatic granularity on this chart for backwards compatibility. This tiny change addresses that issue.
> Fix granularity not being applied correctly for formatting
