embeddable-hq/vanilla-components

- package-lock.json
- package.json
- yarn.lock
Fixed vulnerabilities and updated embeddable packages to the latest versions
There are still 2 vulnerabilities, but they are moderate. These vulnerabilities belong to Cube, so let's wait for them to fix them on their side. 
Also, updating Cube to the latest versions will not fix this issue
https://www.npmjs.com/package/@cubejs-backend/api-gateway/v/0.34.60?activeTab=code
> EM-552: fix vulnerabilities

- .github/workflows/verify-build.yml
This commit sets up a CI/CD pipeline for vanilla-components. Upon each push to the main branch, it installs dependencies, builds embeddable components, and alerts of any errors. It runs on Ubuntu, macOS, and Windows machines for broad compatibility.
- Implemented GitHub Actions workflow YAML file to establish CI/CD pipeline.
- Defined triggers to activate the pipeline upon pushing changes to the main branch.
- Incorporated steps to checkout the main branch, install dependencies using npm, and build embeddable components.
- Added error-checking mechanism to notify users of any encountered issues during the execution.
- Configured the pipeline to run on Ubuntu, macOS, and Windows machines, ensuring compatibility across various environments.
> EM-820: Implement GitHub Actions CI/CD pipeline for vanilla-components to verify build

- .github/workflows/verify-build.yml
This commit implements a feature to send Slack notifications in case of build failures.
- Implemented functionality to send Slack notifications.
- Integrated notification mechanism into the build process.
> EM-820: Add functionality to send slack notification on build failure

- .github/workflows/pull-request-workflow.yml
- .github/workflows/verify-build.yml
This commit sets up a CI/CD pipeline for vanilla-components. Upon each pull-request to the main branch, it installs dependencies, builds embeddable components, and alerts of any errors. It runs on Ubuntu, macOS, and Windows machines for broad compatibility.
> EM-820: Implement GitHub Actions for vanilla-components to verify pull-request

- .github/workflows/verify-build.yml
Cancels concurrent in-progress jobs to save resources
> EM-820: Cancel concurrent jobs

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/dependabot-automerge.yml
Introduces [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to automatically checks `npm` dependencies and updates them daily automatically.
Also, this pull request adds action to automatically merge dependabot dependencies updates.
> EM-863: Introduce dependabot

- .gitignore
- src/components/constants.ts
- src/components/util/getBarChartOptions.ts
- src/components/util/getStackedChartData.ts
- src/components/vanilla/charts/BarChart/index.tsx
- src/components/vanilla/charts/KPIChart/KPIChart.emb.ts
- src/components/vanilla/charts/KPIChart/index.tsx
- src/components/vanilla/charts/PieChart/PieChart.emb.ts
- src/components/vanilla/charts/PieChart/index.tsx
- src/components/vanilla/charts/StackedBarChart/index.tsx
Arbitrary truncation remove for labels and legend items
Better-curated colors replace existing ones (selected by Erin to provide better contrast with both dark and light labels)
KPI chart has a font-size input and more appropriate line spacing
> Minor changes

- package-lock.json
- package.json
- src/components/util/cn.ts
- src/components/util/dataManipulation.ts
- src/components/vanilla/charts/KPIChart/index.tsx
- src/components/vanilla/charts/PivotTable/PivotTable.emb.ts
- src/components/vanilla/charts/PivotTable/PivotTable.tsx
- src/components/vanilla/charts/PivotTable/components/TableCell.tsx
- src/components/vanilla/charts/PivotTable/components/TableHead.tsx
- src/components/vanilla/charts/PivotTable/components/TableRow.tsx
- src/components/vanilla/charts/PivotTable/customInputTypes/MeasureVisualizationFormat.type.emb.ts
- src/components/vanilla/charts/PivotTable/enums/MeasureVisualizationFormat.ts
- src/components/vanilla/charts/PivotTable/enums/TableHeaderType.ts
- src/components/vanilla/charts/PivotTable/index.tsx
- src/components/vanilla/charts/TableChart/index.tsx
- src/enums/SortDirection.ts
- src/models/cubes/products.cube.yml
- src/types/SortDirection.type.emb.ts
- tsconfig.json
- yarn.lock
Added pivot table component that support one or more measures as well as following combinations of rows and columns dimensions:
- 1 row dimension + 0 col dimensions
- 0 row dimensions + 1 col dimensions
- 1 row dimension + 1 col dimension
- default column dimension sort direction
- default row dimension sort direction
- definition of null value character
- ability to display values as numeric values or as a value bars
- specify minimal column width in pixels
- specify minimal column width of row dimension values
https://github.com/embeddable-hq/vanilla-components/assets/5869729/e1d71fbe-dc51-45ba-b4f3-84661d610534
> Add pivot table component

- .github/workflows/pull-request-workflow.yml
- .github/workflows/verify-build.yml
- package.json
- src/components/util/formatDateTooltips.ts
This commit addresses and resolves multiple lint errors across the codebase and enhances the CI/CD workflow to include a step for lint verification. By incorporating these changes, we aim to improve code quality and maintainability, ensuring that future commits adhere to our linting standards.
- Corrected various lint errors throughout the codebase to meet the standards set by our ESLint configuration.
- Modified the CI/CD pipeline configuration to include a linting step.
- Ensured that the pipeline will fail if linting errors are detected, enforcing code quality checks before merging.
https://github.com/embeddable-hq/vanilla-components/assets/23046584/031dfb51-b09c-4bcd-8c63-1daa6935982e
> EM-918: Resolve linting issues and enhance CI workflow to check for linting errors

- src/components/vanilla/charts/PieChart/index.tsx
Erroneous use of formatValue removed
> Pie chart formatValue function removed.

- src/components/vanilla/Description.tsx
- src/components/vanilla/charts/BarChart/BarChart.emb.ts
- src/components/vanilla/charts/CompareLineChart/CompareLineChart.emb.ts
- src/components/vanilla/charts/KPIChart/KPIChart.emb.ts
- src/components/vanilla/charts/LineChart/LineChart.emb.ts
- src/components/vanilla/charts/MapChart/MapChart.emb.ts
- src/components/vanilla/charts/PieChart/PieChart.emb.ts
- src/components/vanilla/charts/PivotTable/PivotTable.emb.ts
- src/components/vanilla/charts/PivotTable/index.tsx
- src/components/vanilla/charts/StackedAreaChart/StackedAreaChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/StackedBarChart.emb.ts
- src/components/vanilla/charts/TableChart/TableChart.emb.ts
- src/components/vanilla/controls/ComparisonFilter/index.tsx
- src/components/vanilla/controls/DateRangePicker/index.tsx
- src/components/vanilla/controls/Dropdown/index.tsx
- src/components/vanilla/index.css
- Add a description input to each chart
- Minor style changes to improve mobile friendliness of comparison component and dropdowns
- Additional relativeTimeString options added
> Description input added to charts (and some minor improvements)

- src/components/vanilla/charts/PivotTable/PivotTable.emb.ts
Add changes for backward compatibility of pivot table
> Pivot table backward compatibility

- package-lock.json
- package.json
- src/components/vanilla/Description.tsx
- src/components/vanilla/Title.tsx
- src/components/vanilla/charts/PieChart/index.tsx
- src/components/vanilla/charts/Text/Text.emb.ts
- src/components/vanilla/charts/Text/index.tsx
- yarn.lock
Update to latest version of SDK
Clicking pie segment twice updates and *re-updates* variable
> Text component font size

- src/components/constants.ts
- src/components/vanilla/Description.tsx
- src/components/vanilla/Title.tsx
- src/components/vanilla/charts/KPIChart/KPIChart.emb.ts
- src/components/vanilla/charts/KPIChart/KPIChartText.emb.ts
- src/components/vanilla/charts/KPIChart/index.tsx
Title and description bottom-margin reduced
Additional consts added for font-sizes and colors
New Text KPI chart added
Download turned off as default for kpi charts
KPI charts renamed to mention number vs text
> Text KPI chart added

- package.json
This commit fixes npm package vulnerabilities.
- Updated `@cubejs-backend/api-gateway` to `0.35.81`
https://github.com/user-attachments/assets/621e54f3-595a-4e46-88c7-411f2237e4cf
> EM-977: Fix npm package vulnerabilities

- package-lock.json
- package.json
- yarn.lock
This commit updates package-lock.json and yarn.lock files
> EM-977: Update package-lock.json and yarn.lock files

- .github/workflows/license-report.yml
Fixes job by setting `BUILD_NODE_VERSION` environment variable
> EM-1090: Fix license-report job

- src/components/vanilla/Container.tsx
Height is always calculated
Titles now show even when 0 results or errors shown.
> Container bug where height wasn't calculated correctly fixed

- .github/workflows/npm-audit.yml
This commit adds node version for `npm-audit` github action.
https://github.com/embeddable-hq/vanilla-components/actions/runs/11239572430/job/31246940409?pr=125
> EM-000: Add node version for npm-audit

- src/components/util/format.ts
wrap will throw an error if the str is ''
> EM-1166: clear inputs fix

- src/components/vanilla/charts/ScatterChart/ScatterChart.emb.ts
- src/components/vanilla/charts/ScatterChart/index.tsx
New scatterplot chart added. 
This chart is very similar to the bubble chart, but doesn't take a 'bubble size' input, and also accepts multiple metrics.
> Scatterplot

- package-lock.json
- src/components/util/downloadAsCSV.ts
- src/components/vanilla/Container.tsx
- src/components/vanilla/DownloadMenu.tsx
- yarn.lock
Fixes [TPS-452](https://trevorio.atlassian.net/issues/TPS-452) - Bug in csv download: it doesn't use the customer-facing header
I introduced this bug by mistake while adding PNG downloads. I missed a set of values that needed to be passed down to the CSV download function so that it could map input titles to customer-facing names. I've fixed this and also improved the TS typing so it's more clear what's required, so if we adjust this functionality any in the future, we should get errors if we're not passing all of the correct data.
- Should use customer-facing titles in CSV headers (tested, works)
- Improve TS types (done)
- No TS errors (none)
[TPS-452]: https://trevorio.atlassian.net/browse/TPS-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
> Fix CSV headers not using friendly titles

- package-lock.json
- package.json
- yarn.lock
Updates core, react, sdk-core, and sdk-react to latest versions.
Shouldn't break anything 🙂
> Update to latest versions of Embeddable tech

- package-lock.json
- package.json
- yarn.lock
`npm audit` was reporting three high-level security vulnerabilities in our dependencies.
**Fix**
Run `npm audit fix --force`, commit resulting repo updates
- `npm audit` reports `0` vulnerabilities
- Build still runs without issue
- Dashboard still runs without issue
... looking good!
> Fix NPM Vulnerabilities

- package-lock.json
- package.json
- src/components/vanilla/charts/PieChart/index.tsx
- src/models/cubes/orders.cube.yml
- yarn.lock
This doesn't actually do much, since most of the effort was on the back-end, but it does introduce a rolling count to the example orders cube so that people can play around with it.
**Screenshots**
Here's a shot of using rolling window to show this month's orders adding to the total
Note for your own testing: rolling windows require both a date-based X-axis AND a date filter. See these settings:
- Code looks good
- Rolling windows work (✅)
> TPS-448 - Rolling Window

- src/components/hooks/useTimeseries.ts
- src/components/vanilla/charts/BarChart/TimeSeriesBarChart.emb.ts
- src/components/vanilla/charts/BubbleChart/BubbleChart.emb.ts
- src/components/vanilla/charts/DynamicAxisBar/DynamicAxisBar.emb.ts
- src/components/vanilla/charts/LineChart/LineChart.emb.ts
- src/components/vanilla/charts/ScatterChart/ScatterChart.emb.ts
- src/components/vanilla/charts/StackedAreaChart/MultiDimensionLineChart.emb.ts
- src/components/vanilla/charts/StackedAreaChart/StackedAreaChart.emb.ts
- src/components/vanilla/charts/StackedBarChart/TimeSeriesStackedBarChart.emb.ts
- yarn.lock
It's not needed (I've removed it and can't find any errors). 
Importantly, this filter prevents pre-aggregations from working correctly.
> Remove filter 'notNulls' from time-series charts. 

- README.md
This commit updated `Readme.md` to add information for environment variable.
- Added information for `CUBE_CLOUD_ENDPOINT` environment variable
> EM-1408: Update README.md

- src/components/vanilla/charts/BubbleChart/index.tsx
- src/components/vanilla/charts/DynamicAxisBar/index.tsx
- src/components/vanilla/charts/PieChart/index.tsx
- src/defaulttheme.ts
This moves the bubble and time series bar charts away from constants and instead uses the new theming system.
> Convert Bubble Chart and Time Series Bar to Themes

- src/components/vanilla/charts/KPIChart/index.tsx
- src/defaulttheme.ts
- yarn.lock
This moves the KPI charts away from constants and instead uses the new theming system.
> Cs 1/charts/kpi

- src/components/vanilla/charts/LineChart/index.tsx
This moves the table charts away from constants and instead uses the new theming system.
> Line Chart Works With Themes

- src/components/vanilla/charts/ScatterChart/index.tsx
This moves the scatter charts away from constants and instead uses the new theming system.
> Wire Scatter Chart Up to Themes

- src/components/util/getStackedChartData.ts
- src/components/vanilla/charts/StackedAreaChart/index.tsx
This moves the table charts away from constants and instead uses the new theming system.
> Stacked Area Chart Uses Themes

- src/components/vanilla/charts/MapChart/index.tsx
This moves the Map Chart away from constants and instead uses the new theming system.
> Map Chart Uses Theme Values

- package-lock.json
- package.json
- src/components/util/chartjs/common.ts
- src/components/vanilla/charts/KPIChart/index.tsx
- src/components/vanilla/charts/MapChart/index.tsx
- src/components/vanilla/charts/PivotTable/PivotTable.tsx
- src/components/vanilla/charts/PivotTable/components/TableHead.tsx
- src/components/vanilla/charts/TableChart/index.tsx
- src/defaulttheme.ts
- yarn.lock
This improves the theme structure and also introduces color generation via tinycolor2
> improve theme layout, color generation

- package-lock.json
- yarn.lock
> Fixes a moderate-level security bug in the Vite package

- package-lock.json
- package.json
- yarn.lock
Updates to our latest SDK versions.
> update to current SDKS

- package-lock.json
- package.json
- yarn.lock
Updates to the latest SDK versions and also fixes a few vulnerabilities that `npm audit` was reporting.
> Update SDK versions and fix security issues

- package-lock.json
- src/components/util/chartjs/common.ts
- src/components/util/downloadAsPNG.ts
- src/components/util/getBarChartOptions.ts
- src/components/vanilla/Button.tsx
- src/components/vanilla/Container.tsx
- src/components/vanilla/DownloadMenu.tsx
- src/components/vanilla/charts/BarChart/components/BarChart.tsx
- src/components/vanilla/charts/BarChart/index.tsx
- src/components/vanilla/charts/DynamicAxisBar/index.tsx
- src/components/vanilla/charts/KPIChart/index.tsx
- src/components/vanilla/charts/LineChart/index.tsx
- src/components/vanilla/charts/PivotTable/PivotTable.tsx
- src/components/vanilla/charts/PivotTable/components/TableHead.tsx
- src/components/vanilla/charts/TableChart/components/Pagination.tsx
- src/components/vanilla/controls/DatePicker/components/DateRangePicker.tsx
- src/components/vanilla/controls/DatePicker/components/DateRangeWithGranularity.tsx
- src/components/vanilla/controls/Dropdown/index.tsx
- src/components/vanilla/controls/MultiSelectButtons/index.tsx
- src/components/vanilla/controls/MultiSelectDropdown/index.tsx
- src/components/vanilla/controls/NumberInput/index.tsx
- src/components/vanilla/controls/TextInput/index.tsx
- src/components/vanilla/icons.tsx
- src/scripts/embedding-preview.cjs
- src/themes/defaulttheme.ts
- src/themes/theme.ts
Additional cleanup, adding more stuff to the theme, etc.
This PR is being merged into the `develop` branch and will not be merged to `main` until we're ready to go live with theming.
> Tweaks to Theming

- package-lock.json
- yarn.lock
Updates packages using `npm audit` to remove security vulnerabilities.
> update packages with npm audit

- package-lock.json
- yarn.lock
NPM identified a vulnerability. NPM Audit fixed it.
> Fix Moderate Vulnerability

- src/components/vanilla/charts/BarChart/BarChart.emb.ts
Adjust the bar chart `emb.ts` file to allow sorting by any dimension or measure, regardless of what the xAxis value is set to, by conditionally adding the sort metric to the loadData request.
> CS-65 - Bar Chart Sorting

- src/components/vanilla/MultiSelector.tsx
- src/components/vanilla/Selector.tsx
- src/components/vanilla/Selector.types.ts
- src/components/vanilla/charts/BarChart/TimeSeriesBarChart.emb.ts
- src/components/vanilla/charts/TableChart/components/TableHead.tsx
- src/components/vanilla/charts/TableChart/index.tsx
- src/components/vanilla/controls/MultiSelectorDimension/MultiSelectorDimension.emb.ts
- src/components/vanilla/controls/MultiSelectorDimension/index.tsx
- src/components/vanilla/controls/MultiSelectorDimensionOrMeasure/MultiSelectorDimensionOrMeasure.emb.ts
- src/components/vanilla/controls/MultiSelectorDimensionOrMeasure/index.tsx
- src/components/vanilla/controls/MultiSelectorMeasure/MultiSelectorMeasure.emb.ts
- src/components/vanilla/controls/MultiSelectorMeasure/index.tsx
- src/components/vanilla/controls/SelectorDimension/SelectorDimension.emb.ts
- src/components/vanilla/controls/SelectorDimension/index.tsx
- src/components/vanilla/controls/SelectorDimensionOrMeasure/SelectorDimensionOrMeasure.emb.ts
- src/components/vanilla/controls/SelectorDimensionOrMeasure/index.tsx
- src/components/vanilla/controls/SelectorMeasure/SelectorMeasure.emb.ts
- src/components/vanilla/controls/SelectorMeasure/index.tsx
- Now we support Dimensions/Measures/DimensionsOrMeasures types.
- Lets create a component selector for each (array and not array)
- Create 2 new reusable components: Selector and MultiSelector
- Create 3 single Selector components - SelectorDimension, SelectorMeasure, SelectorDimensionOrMeasure
- Create 3 multi Selector components - MultiSelectorDimension, MultiSelectorMeasure, MultiSelectorDimensionOrMeasure
- Include variable to be created on each new component
- Include the default values
- Include the change events
- Fix TimeSeriesBarChart.emb.ts
- Fix TableChart and TableHead
https://github.com/user-attachments/assets/a59cfd31-c82a-45fc-9950-09f6bb60d1bc
> EM-2016: New components - dimension/measure/dimensionOrMeasure dropdowns

- src/components/vanilla/controls/MultiSelectorDimension/MultiSelectorDimension.emb.ts
- src/components/vanilla/controls/MultiSelectorDimensionOrMeasure/MultiSelectorDimensionOrMeasure.emb.ts
- src/components/vanilla/controls/MultiSelectorMeasure/MultiSelectorMeasure.emb.ts
- src/components/vanilla/controls/SelectorDimension/SelectorDimension.emb.ts
- src/components/vanilla/controls/SelectorDimensionOrMeasure/SelectorDimensionOrMeasure.emb.ts
- src/components/vanilla/controls/SelectorMeasure/SelectorMeasure.emb.ts
Default values of type dimension/measure/dimensionOrMeasure need to have config of dataset.
https://github.com/user-attachments/assets/f456a7f3-7efd-418e-b82d-3aa7967dfa8c
> EM-2016: default value config

- src/custom-canvas.css
Literally just a file rename, but with some added comments for clarity
> Rename global.css to custom-canvas.css

- src/components/vanilla/charts/TableChart/components/Pagination.tsx
fixes table pagination next button not working when it should
> Fix - Table Pagination
